# Generated by Django 2.1.4 on 2018-12-04 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurants',
            old_name='phone_number',
            new_name='phone',
        )
    ]
